# Generated by Django 5.0.6 on 2024-07-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0005_alter_remarkable_options_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='default_image.png', max_length=3000),
        ),
    ]
